### ISSUE TITLE
[API] Provide description for each method

### ISSUE THREAD

**Issue by Mdrbhatti** [shumail92/RabbitMail#9]
Reference:
http://stackoverflow.com/questions/24284413/webapi-help-page-description

**Comment by shumail92** [comment]
Yeah; already on list :p 

we'll have proper API docs atleast at end :D

**Comment by Mdrbhatti** [comment]
Just making it known here so we don't forget it along the way :dancers:

**Comment by shumail92** [comment]
haha best :D
